"""initial_schema_v2

Revision ID: fdf05b42557c
Revises:
Create Date: 2026-09-03 23:40:07.372239

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdf05b42557c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "airlines",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("code", sa.String(length=10), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("is_scheduled", sa.Boolean(), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("code"),
    )
    op.create_table(
        "atf_prices",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("location", sa.String(length=50), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("price_per_kl", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_atf_prices_date"), "atf_prices", ["date"], unique=False)
    op.create_table(
        "atf_tax_rates",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("tax_type", sa.String(length=50), nullable=False),
        sa.Column("rate", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "benchmark_values",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("period", sa.String(length=20), nullable=False),
        sa.Column("indicator", sa.String(length=100), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("base_year", sa.String(length=20), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("source_version", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_benchmark_values_period"), "benchmark_values", ["period"], unique=False
    )
    op.create_table(
        "methodology_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("base_period", sa.String(length=50), nullable=True),
        sa.Column("anchor_lead_time", sa.String(length=20), nullable=True),
        sa.Column("price_estimator", sa.String(length=50), nullable=True),
        sa.Column("missing_data_method", sa.String(length=50), nullable=True),
        sa.Column("outlier_method", sa.String(length=50), nullable=True),
        sa.Column("weight_method", sa.String(length=50), nullable=True),
        sa.Column("formula", sa.Text(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version"),
    )
    op.create_table(
        "routes",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("origin", sa.String(length=50), nullable=False),
        sa.Column("destination", sa.String(length=50), nullable=False),
        sa.Column("origin_airport", sa.String(length=10), nullable=False),
        sa.Column("destination_airport", sa.String(length=10), nullable=False),
        sa.Column("route_code", sa.String(length=20), nullable=False),
        sa.Column("corridor_type", sa.String(length=50), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("route_code"),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("access_method", sa.String(length=50), nullable=False),
        sa.Column("permission_status", sa.String(length=50), nullable=True),
        sa.Column("tos_status", sa.String(length=50), nullable=True),
        sa.Column("robots_status", sa.String(length=50), nullable=True),
        sa.Column("license_status", sa.String(length=50), nullable=True),
        sa.Column("rate_limit", sa.Integer(), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=True),
        sa.Column("health_status", sa.String(length=50), nullable=True),
        sa.Column("last_reviewed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "validation_results",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("series_evaluated", sa.String(length=50), nullable=True),
        sa.Column("correlation", sa.Float(), nullable=False),
        sa.Column("mae", sa.Float(), nullable=False),
        sa.Column("rmse", sa.Float(), nullable=False),
        sa.Column("directional_accuracy", sa.Float(), nullable=False),
        sa.Column("prototype_series_version", sa.String(length=50), nullable=True),
        sa.Column("benchmark_version", sa.String(length=50), nullable=True),
        sa.Column("methodology_notes", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collection_jobs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("search_date", sa.Date(), nullable=False),
        sa.Column("travel_date", sa.Date(), nullable=False),
        sa.Column("advance_days", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("error_code", sa.String(length=50), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "index_values",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("index_series", sa.String(length=30), nullable=False),
        sa.Column("index_type", sa.String(length=30), nullable=False),
        sa.Column("lead_time_days", sa.Integer(), nullable=False),
        sa.Column("period_start", sa.Date(), nullable=False),
        sa.Column("period_end", sa.Date(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=True),
        sa.Column("index_value", sa.Float(), nullable=False),
        sa.Column("daily_change_pct", sa.Float(), nullable=True),
        sa.Column("weekly_change_pct", sa.Float(), nullable=True),
        sa.Column("monthly_change_pct", sa.Float(), nullable=True),
        sa.Column("coverage_rate", sa.Float(), nullable=True),
        sa.Column("is_low_coverage", sa.Boolean(), nullable=True),
        sa.Column("methodology_version", sa.String(length=50), nullable=True),
        sa.Column("weight_version", sa.String(length=50), nullable=True),
        sa.Column("calculated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_index_lookup",
        "index_values",
        ["index_series", "index_type", "period_start"],
        unique=False,
    )
    op.create_index(
        op.f("ix_index_values_period_start"), "index_values", ["period_start"], unique=False
    )
    op.create_table(
        "raw_payloads",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("collection_job_id", sa.Integer(), nullable=True),
        sa.Column("payload_uri", sa.String(length=255), nullable=False),
        sa.Column("payload_hash", sa.String(length=64), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=True),
        sa.Column("captured_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_raw_payloads_payload_hash"), "raw_payloads", ["payload_hash"], unique=False
    )
    op.create_table(
        "route_weights",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("passenger_volume", sa.Float(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("period", sa.String(length=50), nullable=False),
        sa.Column("methodology_version", sa.String(length=50), nullable=True),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "fare_observations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("route_id", sa.Integer(), nullable=False),
        sa.Column("airline_id", sa.Integer(), nullable=False),
        sa.Column("search_timestamp", sa.DateTime(), nullable=False),
        sa.Column("travel_date", sa.Date(), nullable=False),
        sa.Column("advance_purchase_days", sa.Integer(), nullable=False),
        sa.Column("flight_number", sa.String(length=20), nullable=False),
        sa.Column("cabin_class", sa.String(length=20), nullable=True),
        sa.Column("fare_family", sa.String(length=50), nullable=True),
        sa.Column("stops", sa.Integer(), nullable=True),
        sa.Column("availability_status", sa.String(length=30), nullable=True),
        sa.Column("is_carrier_min_fare", sa.Boolean(), nullable=True),
        sa.Column("base_fare", sa.Float(), nullable=False),
        sa.Column("fuel_surcharge", sa.Float(), nullable=True),
        sa.Column("tax_amount", sa.Float(), nullable=True),
        sa.Column("development_fee", sa.Float(), nullable=True),
        sa.Column("convenience_fee", sa.Float(), nullable=True),
        sa.Column("other_fee", sa.Float(), nullable=True),
        sa.Column("total_fare", sa.Float(), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=True),
        sa.Column("is_synthetic", sa.Boolean(), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("quality_status", sa.String(length=30), nullable=True),
        sa.Column("collector_version", sa.String(length=20), nullable=True),
        sa.Column("schema_version", sa.String(length=20), nullable=True),
        sa.Column("raw_payload_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["airline_id"],
            ["airlines.id"],
        ),
        sa.ForeignKeyConstraint(
            ["raw_payload_id"],
            ["raw_payloads.id"],
        ),
        sa.ForeignKeyConstraint(
            ["route_id"],
            ["routes.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_fare_lookup",
        "fare_observations",
        ["route_id", "travel_date", "advance_purchase_days", "cabin_class"],
        unique=False,
    )
    op.create_index(
        "idx_search_carrier", "fare_observations", ["search_timestamp", "airline_id"], unique=False
    )
    op.create_index(
        op.f("ix_fare_observations_advance_purchase_days"),
        "fare_observations",
        ["advance_purchase_days"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fare_observations_is_carrier_min_fare"),
        "fare_observations",
        ["is_carrier_min_fare"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fare_observations_is_synthetic"),
        "fare_observations",
        ["is_synthetic"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fare_observations_search_timestamp"),
        "fare_observations",
        ["search_timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fare_observations_travel_date"), "fare_observations", ["travel_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_fare_observations_travel_date"), table_name="fare_observations")
    op.drop_index(op.f("ix_fare_observations_search_timestamp"), table_name="fare_observations")
    op.drop_index(op.f("ix_fare_observations_is_synthetic"), table_name="fare_observations")
    op.drop_index(op.f("ix_fare_observations_is_carrier_min_fare"), table_name="fare_observations")
    op.drop_index(
        op.f("ix_fare_observations_advance_purchase_days"), table_name="fare_observations"
    )
    op.drop_index("idx_search_carrier", table_name="fare_observations")
    op.drop_index("idx_fare_lookup", table_name="fare_observations")
    op.drop_table("fare_observations")
    op.drop_table("route_weights")
    op.drop_index(op.f("ix_raw_payloads_payload_hash"), table_name="raw_payloads")
    op.drop_table("raw_payloads")
    op.drop_index(op.f("ix_index_values_period_start"), table_name="index_values")
    op.drop_index("idx_index_lookup", table_name="index_values")
    op.drop_table("index_values")
    op.drop_table("collection_jobs")
    op.drop_table("validation_results")
    op.drop_table("sources")
    op.drop_table("routes")
    op.drop_table("methodology_versions")
    op.drop_index(op.f("ix_benchmark_values_period"), table_name="benchmark_values")
    op.drop_table("benchmark_values")
    op.drop_table("atf_tax_rates")
    op.drop_index(op.f("ix_atf_prices_date"), table_name="atf_prices")
    op.drop_table("atf_prices")
    op.drop_table("airlines")
    # ### end Alembic commands ###
